controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

    steering_controller:
      type: position_controllers/JointGroupPositionController

velocity_controllers:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

steering_controller:
  ros__parameters:
    joints:
      - front_left_steering_joint
      - front_right_steering_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity